In [3]:
import numpy as np
np.version.version

'1.21.5'

In [6]:
a = np.random.rand(2,3,5)

In [7]:
a

array([[[0.22902521, 0.69433276, 0.81278389, 0.67940638, 0.81561891],
        [0.72940906, 0.48907353, 0.70765283, 0.64194879, 0.04665747],
        [0.59637233, 0.63524833, 0.68110169, 0.9798183 , 0.5674549 ]],

       [[0.78991881, 0.13792995, 0.65306104, 0.36568121, 0.45301069],
        [0.41678247, 0.09556341, 0.00483402, 0.11776031, 0.70577521],
        [0.85279465, 0.65715884, 0.49965146, 0.54543032, 0.93800375]]])

In [8]:
b = np.ones((5,2,3))

In [9]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
c = np.reshape(b, (2,3,5))

In [17]:
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [19]:
d = a+c

In [20]:
d

array([[[1.22902521, 1.69433276, 1.81278389, 1.67940638, 1.81561891],
        [1.72940906, 1.48907353, 1.70765283, 1.64194879, 1.04665747],
        [1.59637233, 1.63524833, 1.68110169, 1.9798183 , 1.5674549 ]],

       [[1.78991881, 1.13792995, 1.65306104, 1.36568121, 1.45301069],
        [1.41678247, 1.09556341, 1.00483402, 1.11776031, 1.70577521],
        [1.85279465, 1.65715884, 1.49965146, 1.54543032, 1.93800375]]])

In [21]:
e = a*c

In [22]:
e

array([[[0.22902521, 0.69433276, 0.81278389, 0.67940638, 0.81561891],
        [0.72940906, 0.48907353, 0.70765283, 0.64194879, 0.04665747],
        [0.59637233, 0.63524833, 0.68110169, 0.9798183 , 0.5674549 ]],

       [[0.78991881, 0.13792995, 0.65306104, 0.36568121, 0.45301069],
        [0.41678247, 0.09556341, 0.00483402, 0.11776031, 0.70577521],
        [0.85279465, 0.65715884, 0.49965146, 0.54543032, 0.93800375]]])

In [13]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [24]:
d_max = np.amax(d)
d_max

1.9798182990774267

In [25]:
d_min = np.amin(d)
d_min

1.0048340226715804

In [26]:
d_mean = np.mean(d)
d_mean

1.5513086839216172

In [30]:
f = np.empty((2,3,5))

In [31]:
f

array([[[0.22902521, 0.69433276, 0.81278389, 0.67940638, 0.81561891],
        [0.72940906, 0.48907353, 0.70765283, 0.64194879, 0.04665747],
        [0.59637233, 0.63524833, 0.68110169, 0.9798183 , 0.5674549 ]],

       [[0.78991881, 0.13792995, 0.65306104, 0.36568121, 0.45301069],
        [0.41678247, 0.09556341, 0.00483402, 0.11776031, 0.70577521],
        [0.85279465, 0.65715884, 0.49965146, 0.54543032, 0.93800375]]])

In [32]:
if a.shape == f.shape:
    print (True)

True


In [33]:
len(f)

2

In [34]:
f.shape

(2, 3, 5)